CONTIKI = ../../..

all: example-broadcast example-abc example-mesh example-collect example-trickle example-polite \
     example-rucb example-multihop\
     example-runicast example-unicast example-neighbors

include $(CONTIKI)/Makefile.include
